import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Theme & Design System tokens from design.md
        primary: {
          DEFAULT: "#775a00",
          hover: "#5e4700",
          container: "#f4c95d",
          fixed: "#ffdf97",
          "fixed-dim": "#ecc156",
          soft: "#FFF3C4",
          light: "#FFF9E6",
          dark: "#5a4400",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#6e5400",
        "on-primary-fixed": "#251a00",
        "on-primary-fixed-variant": "#5a4400",
        "primary-container": "#f4c95d",
        "primary-fixed": "#ffdf97",
        "primary-fixed-dim": "#ecc156",
        "inverse-primary": "#ecc156",

        secondary: {
          DEFAULT: "#665f3a",
          container: "#ebe0b2",
          fixed: "#eee3b5",
          "fixed-dim": "#d2c79a",
        },
        "on-secondary": "#ffffff",
        "secondary-container": "#ebe0b2",
        "on-secondary-container": "#6b633e",
        "secondary-fixed": "#eee3b5",
        "secondary-fixed-dim": "#d2c79a",
        "on-secondary-fixed": "#211b01",
        "on-secondary-fixed-variant": "#4e4725",

        tertiary: {
          DEFAULT: "#006687",
          container: "#8cd8ff",
          fixed: "#c1e8ff",
          "fixed-dim": "#84d0f7",
        },
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8cd8ff",
        "on-tertiary-container": "#005f7e",
        "tertiary-fixed": "#c1e8ff",
        "tertiary-fixed-dim": "#84d0f7",
        "on-tertiary-fixed": "#001e2b",
        "on-tertiary-fixed-variant": "#004d67",

        surface: "#FFFFFF",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#775a00",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4e4636",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",

        background: "#FFFDF8",
        "on-background": "#1b1c1c",
        border: "#EDE8DA",
        outline: "#7f7664",
        "outline-variant": "#d1c5b0",

        "text-secondary": "#6B6B6B",
        text: {
          primary: "#1b1c1c",
          secondary: "#6B6B6B",
          muted: "#8c877d",
        },

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "error-soft": "#FFEBEE",

        "success-soft": "#E8F5E9",
        "success-dark": "#2e7d32",
        "warning-soft": "#FFF3E0",

        accent: {
          green: "#2e7d32",
          greenSoft: "#E8F5E9",
          orange: "#d97706",
          orangeSoft: "#FFF3E0",
          red: "#ba1a1a",
          redSoft: "#FFEBEE",
          blue: "#006687",
          blueSoft: "#c1e8ff",
        },
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "Plus Jakarta Sans", "Inter", "sans-serif"],
        "hero-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "section-title": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "button-text": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "hero-lg": ["56px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "hero-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "section-title": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "1", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      spacing: {
        "container-max": "1280px",
        unit: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      boxShadow: {
        soft: "0 1px 8px rgba(0, 0, 0, 0.04)",
        card: "0 10px 30px rgba(37, 37, 37, 0.05)",
        float: "0 15px 40px rgba(37, 37, 37, 0.08)",
        glow: "0 0 24px rgba(244, 201, 93, 0.45)",
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
